apiVersion: v1
kind: ConfigMap
metadata:
  name: "timescaledb-backup-hook-config-map"
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
data:
  entrypoint.sh: |-
    #!/bin/sh
    cmd="/docker-entrypoint.sh timescaledb"
    eval "${cmd}" & disown;
    until pg_isready; do
      sleep 5;
    done;
    pg_dump -U {{ .Values.postgresqlUser }} -d {{ .Values.postgresqlDatabase }} > /dbbackups/$BACKUP_NAME;
